export interface User {
  id: string;
  name: string;
  email: string;
  role: "client" | "lawyer";
  status: "active" | "inactive" | "pending";
  joinedDate: string;
  consultations: number;
}

export interface DashboardStats {
  totalUsers: number;
  totalLawyers: number;
  totalClients: number;
  activeConsultations: number;
  totalRevenue: number;
  pendingApprovals: number;
  consultationsToday: number;
  avgRating: number;
}

export const dashboardStats: DashboardStats = {
  totalUsers: 2847,
  totalLawyers: 342,
  totalClients: 2505,
  activeConsultations: 18,
  totalRevenue: 128450,
  pendingApprovals: 12,
  consultationsToday: 47,
  avgRating: 4.8,
};

export const recentActivity = [
  { id: "1", action: "New lawyer registered", name: "Sarah Mitchell", time: "2 min ago" },
  { id: "2", action: "Consultation completed", name: "John Davis", time: "15 min ago" },
  { id: "3", action: "Payment received", name: "Maria Garcia", time: "32 min ago" },
  { id: "4", action: "New client signup", name: "Alex Thompson", time: "1 hr ago" },
  { id: "5", action: "Lawyer verified", name: "Robert Chen", time: "2 hr ago" },
  { id: "6", action: "Consultation started", name: "Emily Watson", time: "3 hr ago" },
];

export const users: User[] = [
  { id: "1", name: "Sarah Mitchell", email: "sarah.mitchell@email.com", role: "lawyer", status: "active", joinedDate: "2025-11-15", consultations: 87 },
  { id: "2", name: "John Davis", email: "john.davis@email.com", role: "client", status: "active", joinedDate: "2025-12-03", consultations: 5 },
  { id: "3", name: "Maria Garcia", email: "maria.garcia@email.com", role: "client", status: "active", joinedDate: "2026-01-08", consultations: 12 },
  { id: "4", name: "Robert Chen", email: "robert.chen@email.com", role: "lawyer", status: "pending", joinedDate: "2026-01-22", consultations: 0 },
  { id: "5", name: "Emily Watson", email: "emily.watson@email.com", role: "client", status: "active", joinedDate: "2025-10-19", consultations: 23 },
  { id: "6", name: "Alex Thompson", email: "alex.thompson@email.com", role: "lawyer", status: "active", joinedDate: "2025-09-05", consultations: 145 },
  { id: "7", name: "Lisa Park", email: "lisa.park@email.com", role: "client", status: "inactive", joinedDate: "2025-08-12", consultations: 3 },
  { id: "8", name: "James Wilson", email: "james.wilson@email.com", role: "lawyer", status: "active", joinedDate: "2025-07-28", consultations: 201 },
  { id: "9", name: "Priya Patel", email: "priya.patel@email.com", role: "client", status: "active", joinedDate: "2026-01-30", consultations: 1 },
  { id: "10", name: "David Kim", email: "david.kim@email.com", role: "lawyer", status: "pending", joinedDate: "2026-02-01", consultations: 0 },
  { id: "11", name: "Rachel Adams", email: "rachel.adams@email.com", role: "client", status: "active", joinedDate: "2025-12-20", consultations: 8 },
  { id: "12", name: "Michael Brown", email: "michael.brown@email.com", role: "lawyer", status: "active", joinedDate: "2025-06-14", consultations: 312 },
];

// ─── Disputes ────────────────────────────────────────────────────────
import type { AdminDispute } from "./api";

export const mockDisputes: AdminDispute[] = [
  {
    id: "disp-001",
    consultationId: "cons-101",
    category: "BILLING",
    description: "I was charged $350 for a 15-minute consultation that was supposed to be a free trial. The lawyer did not inform me that the trial had ended before continuing the session.",
    status: "OPEN",
    resolutionType: null,
    resolutionNote: null,
    refundAmount: null,
    lawyerDeadline: "2026-02-18T00:00:00.000Z",
    mediationDeadline: null,
    resolvedAt: null,
    createdAt: "2026-02-10T14:30:00.000Z",
    filedBy: { firstName: "Maria", lastName: "Garcia" },
    filedAgainst: { firstName: "Sarah", lastName: "Mitchell" },
    consultation: { id: "cons-101", category: "Family Law", payment: { amount: 35000, status: "COMPLETED" } },
  },
  {
    id: "disp-002",
    consultationId: "cons-102",
    category: "SERVICE_QUALITY",
    description: "The lawyer was 30 minutes late to our scheduled video consultation and then rushed through the remaining time. I did not receive adequate legal advice for the amount paid.",
    status: "MEDIATION",
    resolutionType: null,
    resolutionNote: null,
    refundAmount: null,
    lawyerDeadline: "2026-02-12T00:00:00.000Z",
    mediationDeadline: "2026-02-20T00:00:00.000Z",
    resolvedAt: null,
    createdAt: "2026-02-05T09:15:00.000Z",
    filedBy: { firstName: "John", lastName: "Davis" },
    filedAgainst: { firstName: "Alex", lastName: "Thompson" },
    consultation: { id: "cons-102", category: "Criminal Defense", payment: { amount: 50000, status: "COMPLETED" } },
  },
  {
    id: "disp-003",
    consultationId: "cons-103",
    category: "MISCONDUCT",
    description: "The lawyer shared confidential information from our consultation with a third party. I have evidence of this through an email that was accidentally CC'd to me.",
    status: "ESCALATED",
    resolutionType: null,
    resolutionNote: null,
    refundAmount: null,
    lawyerDeadline: "2026-01-30T00:00:00.000Z",
    mediationDeadline: "2026-02-08T00:00:00.000Z",
    resolvedAt: null,
    createdAt: "2026-01-25T16:45:00.000Z",
    filedBy: { firstName: "Emily", lastName: "Watson" },
    filedAgainst: { firstName: "James", lastName: "Wilson" },
    consultation: { id: "cons-103", category: "Business Law", payment: { amount: 75000, status: "COMPLETED" } },
  },
  {
    id: "disp-004",
    consultationId: "cons-104",
    category: "BILLING",
    description: "I was double-charged for the same consultation. Two payments of $200 were taken from my account on the same day.",
    status: "RESOLVED",
    resolutionType: "FULL_REFUND",
    resolutionNote: "Duplicate charge confirmed. Full refund of $200 issued to client's payment method.",
    refundAmount: 20000,
    lawyerDeadline: null,
    mediationDeadline: null,
    resolvedAt: "2026-02-03T11:00:00.000Z",
    createdAt: "2026-01-28T10:20:00.000Z",
    filedBy: { firstName: "Priya", lastName: "Patel" },
    filedAgainst: { firstName: "Robert", lastName: "Chen" },
    consultation: { id: "cons-104", category: "Immigration", payment: { amount: 20000, status: "REFUNDED" } },
  },
  {
    id: "disp-005",
    consultationId: "cons-105",
    category: "NO_SHOW",
    description: "The lawyer did not show up for our scheduled consultation. I waited 45 minutes and received no communication or apology.",
    status: "RESOLVED",
    resolutionType: "FULL_REFUND",
    resolutionNote: "No-show confirmed via system logs. Full refund issued and lawyer received a warning.",
    refundAmount: 15000,
    lawyerDeadline: null,
    mediationDeadline: null,
    resolvedAt: "2026-01-22T15:30:00.000Z",
    createdAt: "2026-01-18T08:00:00.000Z",
    filedBy: { firstName: "Rachel", lastName: "Adams" },
    filedAgainst: { firstName: "Sarah", lastName: "Mitchell" },
    consultation: { id: "cons-105", category: "Estate Planning", payment: { amount: 15000, status: "REFUNDED" } },
  },
  {
    id: "disp-006",
    consultationId: "cons-106",
    category: "SERVICE_QUALITY",
    description: "The advice provided was generic and unhelpful. The lawyer clearly had no expertise in tax law despite listing it as a specialization.",
    status: "CLOSED",
    resolutionType: "PARTIAL_REFUND",
    resolutionNote: "After review, a 50% refund was issued. Lawyer's tax law specialization was flagged for re-verification.",
    refundAmount: 12500,
    lawyerDeadline: null,
    mediationDeadline: null,
    resolvedAt: "2026-01-15T14:00:00.000Z",
    createdAt: "2026-01-08T11:30:00.000Z",
    filedBy: { firstName: "David", lastName: "Kim" },
    filedAgainst: { firstName: "Michael", lastName: "Brown" },
    consultation: { id: "cons-106", category: "Tax Law", payment: { amount: 25000, status: "PARTIALLY_REFUNDED" } },
  },
  {
    id: "disp-007",
    consultationId: "cons-107",
    category: "BILLING",
    description: "I cancelled the consultation within the 24-hour free cancellation window but was still charged the full amount.",
    status: "OPEN",
    resolutionType: null,
    resolutionNote: null,
    refundAmount: null,
    lawyerDeadline: "2026-02-16T00:00:00.000Z",
    mediationDeadline: null,
    resolvedAt: null,
    createdAt: "2026-02-09T17:00:00.000Z",
    filedBy: { firstName: "Lisa", lastName: "Park" },
    filedAgainst: { firstName: "Alex", lastName: "Thompson" },
    consultation: { id: "cons-107", category: "Real Estate", payment: { amount: 30000, status: "COMPLETED" } },
  },
  {
    id: "disp-008",
    consultationId: "cons-108",
    category: "MISCONDUCT",
    description: "The lawyer was rude and dismissive during our consultation. They made inappropriate comments about my case and seemed disinterested in helping.",
    status: "CLOSED",
    resolutionType: "DISMISSED",
    resolutionNote: "After reviewing the consultation recording, the complaint was not substantiated. No refund issued.",
    refundAmount: null,
    lawyerDeadline: null,
    mediationDeadline: null,
    resolvedAt: "2026-01-20T09:45:00.000Z",
    createdAt: "2026-01-10T13:15:00.000Z",
    filedBy: { firstName: "Alex", lastName: "Thompson" },
    filedAgainst: { firstName: "James", lastName: "Wilson" },
    consultation: { id: "cons-108", category: "Personal Injury", payment: { amount: 40000, status: "COMPLETED" } },
  },
];

// ─── Reports ─────────────────────────────────────────────────────────
import type { AdminReport } from "./api";

export const mockReports: AdminReport[] = [
  {
    id: "rpt-001",
    reason: "SPAM",
    description: "This user has been sending unsolicited messages to multiple lawyers offering SEO services through the platform's messaging system.",
    status: "PENDING",
    resolution: null,
    createdAt: "2026-02-11T10:00:00.000Z",
    reporter: { firstName: "Sarah", lastName: "Mitchell" },
    reported: { firstName: "Tom", lastName: "Spencer" },
  },
  {
    id: "rpt-002",
    reason: "HARASSMENT",
    description: "After I declined to take their case, this client sent multiple abusive messages including threats to leave fake reviews.",
    status: "PENDING",
    resolution: null,
    createdAt: "2026-02-10T08:30:00.000Z",
    reporter: { firstName: "James", lastName: "Wilson" },
    reported: { firstName: "Kevin", lastName: "Hart" },
  },
  {
    id: "rpt-003",
    reason: "FRAUD",
    description: "This person is impersonating a licensed attorney. I checked the bar number they provided and it belongs to a different individual.",
    status: "REVIEWED",
    resolution: null,
    createdAt: "2026-02-08T14:20:00.000Z",
    reporter: { firstName: "Maria", lastName: "Garcia" },
    reported: { firstName: "Brian", lastName: "Fake" },
  },
  {
    id: "rpt-004",
    reason: "INAPPROPRIATE_CONTENT",
    description: "This lawyer's profile contains misleading claims about their win rate and case outcomes that appear to be fabricated.",
    status: "REVIEWED",
    resolution: null,
    createdAt: "2026-02-06T16:45:00.000Z",
    reporter: { firstName: "Emily", lastName: "Watson" },
    reported: { firstName: "Michael", lastName: "Brown" },
  },
  {
    id: "rpt-005",
    reason: "HARASSMENT",
    description: "Received repeated unwanted phone calls outside of consultation hours. The lawyer keeps calling despite being asked to stop.",
    status: "ACTIONED",
    resolution: "Warning issued to the lawyer. Phone communication restricted to in-app messaging only.",
    createdAt: "2026-02-01T09:00:00.000Z",
    reporter: { firstName: "Priya", lastName: "Patel" },
    reported: { firstName: "Robert", lastName: "Chen" },
  },
  {
    id: "rpt-006",
    reason: "FRAUD",
    description: "This client provided a fake identity during registration. Their name and photo do not match the ID on file.",
    status: "ACTIONED",
    resolution: "Account suspended pending identity re-verification. User notified via email.",
    createdAt: "2026-01-28T11:30:00.000Z",
    reporter: { firstName: "Alex", lastName: "Thompson" },
    reported: { firstName: "Jane", lastName: "Doe" },
  },
  {
    id: "rpt-007",
    reason: "SPAM",
    description: "This user is posting the same legal question to every lawyer on the platform just to get free consultations.",
    status: "DISMISSED",
    resolution: "Reviewed the activity — user was genuinely seeking help from multiple lawyers. No policy violation.",
    createdAt: "2026-01-25T15:00:00.000Z",
    reporter: { firstName: "Sarah", lastName: "Mitchell" },
    reported: { firstName: "Rachel", lastName: "Adams" },
  },
  {
    id: "rpt-008",
    reason: "INAPPROPRIATE_CONTENT",
    description: "Lawyer's profile bio contains political opinions and controversial statements that are unprofessional.",
    status: "DISMISSED",
    resolution: "While unprofessional, content does not violate platform terms. Recommendation sent to lawyer to update bio.",
    createdAt: "2026-01-20T13:10:00.000Z",
    reporter: { firstName: "John", lastName: "Davis" },
    reported: { firstName: "James", lastName: "Wilson" },
  },
  {
    id: "rpt-009",
    reason: "HARASSMENT",
    description: "This client left a series of defamatory reviews on my profile after I refused to continue working on their case pro bono.",
    status: "PENDING",
    resolution: null,
    createdAt: "2026-02-09T19:00:00.000Z",
    reporter: { firstName: "Michael", lastName: "Brown" },
    reported: { firstName: "Lisa", lastName: "Park" },
  },
  {
    id: "rpt-010",
    reason: "FRAUD",
    description: "This lawyer is advertising services at one price but charging significantly more after the consultation begins.",
    status: "PENDING",
    resolution: null,
    createdAt: "2026-02-11T07:45:00.000Z",
    reporter: { firstName: "David", lastName: "Kim" },
    reported: { firstName: "Alex", lastName: "Thompson" },
  },
];

// ─── Support Tickets ─────────────────────────────────────────────────
import type { AdminTicket } from "./api";

export const mockTickets: AdminTicket[] = [
  {
    id: "tkt-001",
    userId: "usr-001",
    category: "BILLING",
    subject: "Refund not received after 7 days",
    description: "I was approved for a refund on January 30th for consultation #cons-104, but the money has not appeared in my bank account yet. The confirmation email said it would take 3-5 business days. It's been over a week now.",
    status: "OPEN",
    createdAt: "2026-02-08T10:00:00.000Z",
    updatedAt: "2026-02-08T10:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "Priya", lastName: "Patel", email: "priya.patel@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-001",
        ticketId: "tkt-001",
        userId: "usr-001",
        message: "Just checking — any update on this? I still haven't received the refund.",
        isAdmin: false,
        createdAt: "2026-02-10T09:00:00.000Z",
        user: { firstName: "Priya", lastName: "Patel" },
      },
    ],
    _count: { replies: 1 },
  },
  {
    id: "tkt-002",
    userId: "usr-002",
    category: "TECHNICAL",
    subject: "Video call keeps disconnecting",
    description: "Every time I try to start a video consultation, the call connects for about 30 seconds and then drops. I've tried on both WiFi and cellular data. My internet speed is 50+ Mbps. This has happened with the last 3 consultations I've attempted.",
    status: "IN_PROGRESS",
    createdAt: "2026-02-06T14:30:00.000Z",
    updatedAt: "2026-02-09T11:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "John", lastName: "Davis", email: "john.davis@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-002",
        ticketId: "tkt-002",
        userId: "admin-001",
        message: "Thank you for reporting this. Could you please share your device model and OS version? Also, are you using the latest version of the app?",
        isAdmin: true,
        createdAt: "2026-02-07T09:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
      {
        id: "reply-003",
        ticketId: "tkt-002",
        userId: "usr-002",
        message: "I'm using an iPhone 15 Pro on iOS 18.3. App version is 2.1.4 from the App Store.",
        isAdmin: false,
        createdAt: "2026-02-07T10:30:00.000Z",
        user: { firstName: "John", lastName: "Davis" },
      },
      {
        id: "reply-004",
        ticketId: "tkt-002",
        userId: "admin-001",
        message: "We've identified a known issue with the WebRTC connection on iOS 18.3. Our engineering team is working on a fix. In the meantime, please try using the app on a different device or switch to audio-only mode.",
        isAdmin: true,
        createdAt: "2026-02-09T11:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
    ],
    _count: { replies: 3 },
  },
  {
    id: "tkt-003",
    userId: "usr-003",
    category: "ACCOUNT",
    subject: "Cannot update my profile information",
    description: "I'm trying to update my phone number and address on my lawyer profile, but the save button does nothing when I click it. No error message appears either. This has been happening for the past two days.",
    status: "OPEN",
    createdAt: "2026-02-09T16:00:00.000Z",
    updatedAt: "2026-02-09T16:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "Sarah", lastName: "Mitchell", email: "sarah.mitchell@email.com", role: "LAWYER" },
    replies: [],
    _count: { replies: 0 },
  },
  {
    id: "tkt-004",
    userId: "usr-004",
    category: "LEGAL",
    subject: "How do I file a dispute against a lawyer?",
    description: "I had a bad experience with a consultation and I'd like to file a formal complaint. I can't find the option in the app to do this. Can you help me understand the process?",
    status: "RESOLVED",
    createdAt: "2026-02-01T08:45:00.000Z",
    updatedAt: "2026-02-02T10:00:00.000Z",
    resolvedAt: "2026-02-02T10:00:00.000Z",
    user: { firstName: "Emily", lastName: "Watson", email: "emily.watson@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-005",
        ticketId: "tkt-004",
        userId: "admin-001",
        message: "To file a dispute, go to My Consultations → tap on the consultation → scroll down and tap \"Report an Issue\". You can select the category and describe your concern. The dispute will be reviewed within 48 hours. Let me know if you need further help!",
        isAdmin: true,
        createdAt: "2026-02-01T11:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
      {
        id: "reply-006",
        ticketId: "tkt-004",
        userId: "usr-004",
        message: "Found it, thank you so much! I've submitted the dispute.",
        isAdmin: false,
        createdAt: "2026-02-02T09:30:00.000Z",
        user: { firstName: "Emily", lastName: "Watson" },
      },
    ],
    _count: { replies: 2 },
  },
  {
    id: "tkt-005",
    userId: "usr-005",
    category: "BILLING",
    subject: "Charged twice for the same consultation",
    description: "I see two charges of $250 on my credit card statement for consultation #cons-112. Both charges are dated February 3rd. Please investigate and refund the duplicate charge.",
    status: "RESOLVED",
    createdAt: "2026-02-04T12:00:00.000Z",
    updatedAt: "2026-02-05T14:30:00.000Z",
    resolvedAt: "2026-02-05T14:30:00.000Z",
    user: { firstName: "Rachel", lastName: "Adams", email: "rachel.adams@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-007",
        ticketId: "tkt-005",
        userId: "admin-001",
        message: "We've confirmed the duplicate charge and initiated a refund of $250.00. It should appear in your account within 3-5 business days. We apologize for the inconvenience.",
        isAdmin: true,
        createdAt: "2026-02-05T14:30:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
    ],
    _count: { replies: 1 },
  },
  {
    id: "tkt-006",
    userId: "usr-006",
    category: "TECHNICAL",
    subject: "Push notifications not working",
    description: "I'm not receiving any push notifications for messages or consultation updates. I've checked my phone settings and notifications are enabled for the app. I'm on Android 15.",
    status: "IN_PROGRESS",
    createdAt: "2026-02-07T18:00:00.000Z",
    updatedAt: "2026-02-08T09:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "David", lastName: "Kim", email: "david.kim@email.com", role: "LAWYER" },
    replies: [
      {
        id: "reply-008",
        ticketId: "tkt-006",
        userId: "admin-001",
        message: "We're looking into this. Could you try going to Settings → Notifications in the app and toggling the notifications off and back on? This re-registers your push token.",
        isAdmin: true,
        createdAt: "2026-02-08T09:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
    ],
    _count: { replies: 1 },
  },
  {
    id: "tkt-007",
    userId: "usr-007",
    category: "ACCOUNT",
    subject: "Verification taking too long",
    description: "I submitted my bar license and ID verification documents over two weeks ago and my account is still showing as 'Pending Verification'. I'm losing potential clients because I can't accept consultations.",
    status: "OPEN",
    createdAt: "2026-02-10T07:30:00.000Z",
    updatedAt: "2026-02-10T07:30:00.000Z",
    resolvedAt: null,
    user: { firstName: "Robert", lastName: "Chen", email: "robert.chen@email.com", role: "LAWYER" },
    replies: [],
    _count: { replies: 0 },
  },
  {
    id: "tkt-008",
    userId: "usr-008",
    category: "OTHER",
    subject: "Feature request: Calendar integration",
    description: "It would be really helpful if the app could sync consultation schedules with Google Calendar or Apple Calendar. This way I can manage my availability more efficiently.",
    status: "CLOSED",
    createdAt: "2026-01-20T11:00:00.000Z",
    updatedAt: "2026-01-21T16:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "Alex", lastName: "Thompson", email: "alex.thompson@email.com", role: "LAWYER" },
    replies: [
      {
        id: "reply-009",
        ticketId: "tkt-008",
        userId: "admin-001",
        message: "Thank you for the suggestion! We've added this to our product roadmap. Calendar integration is something we're actively working on and hope to release in the next major update.",
        isAdmin: true,
        createdAt: "2026-01-21T16:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
    ],
    _count: { replies: 1 },
  },
  {
    id: "tkt-009",
    userId: "usr-009",
    category: "LEGAL",
    subject: "Need consultation recording for court",
    description: "I need a copy of the recording from my consultation on January 15th (consultation #cons-120). My attorney has requested it as evidence for my ongoing case. How can I obtain this?",
    status: "IN_PROGRESS",
    createdAt: "2026-02-03T13:00:00.000Z",
    updatedAt: "2026-02-04T10:00:00.000Z",
    resolvedAt: null,
    user: { firstName: "Lisa", lastName: "Park", email: "lisa.park@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-010",
        ticketId: "tkt-009",
        userId: "admin-001",
        message: "Consultation recordings can be requested through our data access form. I'll send you a link via email. Please note that we'll need written consent from the lawyer as well, per our privacy policy. Processing typically takes 5-7 business days.",
        isAdmin: true,
        createdAt: "2026-02-04T10:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
    ],
    _count: { replies: 1 },
  },
  {
    id: "tkt-010",
    userId: "usr-010",
    category: "BILLING",
    subject: "How to update payment method",
    description: "My credit card expired and I need to update my payment information. I can't find where to do this in the app settings.",
    status: "RESOLVED",
    createdAt: "2026-01-30T15:00:00.000Z",
    updatedAt: "2026-01-30T17:00:00.000Z",
    resolvedAt: "2026-01-30T17:00:00.000Z",
    user: { firstName: "Maria", lastName: "Garcia", email: "maria.garcia@email.com", role: "CLIENT" },
    replies: [
      {
        id: "reply-011",
        ticketId: "tkt-010",
        userId: "admin-001",
        message: "You can update your payment method by going to Profile → Payment Settings → Manage Payment Methods. Tap 'Add New Card' and enter your updated details. You can then remove the expired card. Let me know if you need more help!",
        isAdmin: true,
        createdAt: "2026-01-30T16:00:00.000Z",
        user: { firstName: "Admin", lastName: "Support" },
      },
      {
        id: "reply-012",
        ticketId: "tkt-010",
        userId: "usr-010",
        message: "Got it, updated successfully. Thanks for the quick response!",
        isAdmin: false,
        createdAt: "2026-01-30T17:00:00.000Z",
        user: { firstName: "Maria", lastName: "Garcia" },
      },
    ],
    _count: { replies: 2 },
  },
];
